### ISSUE TITLE
[3Di]: One channel can have only 1 type of cross section

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-modelchecker#106]
@caspervdw commented on [Tue Nov 02 2021](https://github.com/nens/threedi-api/issues/1214)

### Incident Type

Wish

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?

Excerpt from email from @nvolp:

> - op eenzelfde kanaal moeten dezelfde type crossecties zitten: bijvoorbeeld geen cirkel aan een tabulated cross-sectie. 

### How to Reproduce?

-

### What did you expect and what was the actual result?

-

**Comment by caspervdw** [comment]
Added check: 
- per channel, the drain_level should be all-NULL or all-value. If only 1 has a value and another has NULL, the value is ignored.

**Comment by Jonasvsl** [comment]
Now this is possible 
invalid

**Comment by caspervdw** [comment]
@Jonasvsl Really ? Can you combine a circular and square crosssection on the same  channel?

**Comment by Jonasvsl** [comment]
this is what @martijn-siemerink said
