### ISSUE TITLE
[Bug]: Checker wrongly says drain level is a requirement

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#114]
### Complexity

easy

### Priority

high prio

### What happened?

when a drain level is NULL the checker says this:

Manhole.drain_level cannot be null when Manhole.calculation_type is CONNECTED

it shouldn't say that. the check has to be removed

**Comment by caspervdw** [comment]
@Jonasvsl  This was already fixed in master. The check is now more specific:

> CONNECTED Manhole.drain_level cannot be null when using sub-basins (v2_global_settings.manhole_storage_area > 0) and no DEM is supplied.

Also, the checker warns if Manhole.drain_level >= Manhole.bottom_level
