### ISSUE TITLE
[3Di]: schematisation checker should check for unique entries in the aggregation values

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#121]
### Incident Type

Error

### 3Di component

Model repositories / inpy

### What happened?

I typed the same aggregation setting twice. No checker finds this an issue but the calculation core does.

Please check for uniqueness of flow variables in the v2_aggregation table 

### How to Reproduce?

I typed the same aggregation setting twice. No checker finds this an issue but the calculation core does.

Please check for uniqueness of flow variables in the v2_aggregation table 

### What did you expect and what was the actual result?

I typed the same aggregation setting twice. No checker finds this an issue but the calculation core does.

Please check for uniqueness of flow variables in the v2_aggregation table 

### Additional info

Anything else you would like to share?

**Comment by caspervdw** [comment]
Duplicate of #202
