### ISSUE TITLE
[3Di]: Lonely manhole with connection node gives issues in inpy

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#123]
### Incident Type

Feedback

### What priority should we assign to this submission?

To be determined (Default)

### 3Di component

Model repositories / inpy

### What happened?

RebeccaL
ik heb weer een error gevonden in INPY die er niet uit wordt gehaald door de schematisatiechecker. 
Het gaat om de volgende error
 ** ERROR  : Manhole surface level is below bottom level, Calculation node =  3763,  bottom level =     -6.0000,  drain level =  -9999.0000

Belangrijk hierbij is dat ik niet 1 manhole had waarvan daadwerkelijk de drain level lager was dan de bottom level (in de tabel). Het kwam daarom ook niet uit de schematisatiechecker (want als je dat wel hebt, komt dat er wel uit). Wat ik wel had is een losliggende connection node waar wel een manhole op zat, maar verder geen kunstwerken of leidingen. Denk dat het een goeie toevoeging is om ook te checken op connection nodes waar wel een manhole op zit, maar verder niks. 

### How to Reproduce?

Voor reproductie en uitgebreide log: zutphen-zutphen_default-29-a9739bf1daaaf596b6c4ef52d8680e81ba80982e

### What did you expect and what was the actual result?

I expected a proper Error in the modelchecker

**Comment by caspervdw** [comment]
Deze check zit erin.
