### ISSUE TITLE
Modelchecker should check if table_step_size_1d and/or table_step_size_volume_2d is not 0

### ISSUE THREAD

**Issue by Overmeen** [nens/threedi-modelchecker#124]
### Contact Details

stijn.overmeen@nelen-schuurmans.nl

### Complexity

moderate

### Priority

medium prio

### What happened?

Service desk ticket 2112 0078. 

Table_step_size_1d and table_step_size_volume_2d were set to 0. 

Resulted in Fortran Error -11, once a simulation was started.

This should either be a value higher than 0 or left empty. If empty it will adapt the value of table_step_size in the 'Grid' tab.

This should be checked by the modelchecker.

**Comment by caspervdw** [comment]
Have you checked with the latest version?

The latest release contains these checks:

https://github.com/nens/threedi-modelchecker/blob/master/threedi_modelchecker/config.py#L671

**Comment by Overmeen** [comment]
Hi Casper, the range check shows just a min value of 0. My point was that this can never be 0.

**Comment by caspervdw** [comment]
There is a keyword argument `left_inclusive` to this check, which is set to False. That means that 0 itself is not considered valid.

See here for an explanation: https://github.com/nens/threedi-modelchecker/blob/dfdac823b45ee0b5ae71c8ba33494d46da527639/threedi_modelchecker/checks/base.py#L364
