### ISSUE TITLE
user has infiltration rasters defined but no simple infiltration referral in the global settings

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#168]
we need a warning for that, chances are high that it is a mistake:
![image](https://user-images.githubusercontent.com/1453159/155720893-50e9fbd5-f613-4be9-bdc2-ffbeaf3e777d.png)

![image](https://user-images.githubusercontent.com/1453159/155720920-ec592da5-bc3e-463d-8b36-98505f4c9bd8.png)

This model / revision has this issue:
https://management.3di.live/schematisations/5110/38561

**Comment by caspervdw** [comment]
There are schematizations that have "extended" settings (interflow, simple infiltration, groundwater, numerical settings) that aren't uses. This is not a problem per se. A user may want to disable groundwater or simple infiltration.

So I don't see anything to fix here @Jonasvsl

**Comment by caspervdw** [comment]
Answer found in https://github.com/nens/threedi-modelchecker/issues/236

> If e.g. a record in the v2_simple_infiltration table exists but is not referenced from v2_global_settings, please show this. I think it should be INFO level, because it may be a perfectly valid and intended thing to do

**Comment by elisallenens** [comment]
Should the check also run for v2_global_settings.control_group_id?
