### ISSUE TITLE
Create check for closed and open cross-section on same object

### ISSUE THREAD

**Issue by martijn-siemerink** [nens/threedi-modelchecker#179]
Cross-sections of open configuration and Cross-sections of closed configuration cannot be present on the same object (channel, ~culvert, pipe, weir, orifice~).

Cross-section with a closed configuration are:
- Circle (2)
- Rectangle closed (0)
- Tabulated rectangle (5) with width 0 at highest increment.
- Tabulated trapezium (6) with width 0 at highest increment.
- YZ (7) with first coordinate == last coordinate
- Egg (3)
- Inverted egg (8)

Cross-sections with an open configuration are:
- Rectangle (1)
- Tabulated rectangle (5) with width > 0 at highest increment.
- Tabulated trapezium (6) with width > 0 at highest increment.
- YZ (7) with first coordinate != last coordinate

**Comment by caspervdw** [comment]
Also the new YZ profiles should be incorporated in the check.

**Comment by elisallenens** [comment]
@martijn-siemerink If a cross-section doesn't match any of the conditions above, should the default to fall back to be open or closed?
