### ISSUE TITLE
Handle stricter constraint checking on spatialite 3 -> 4 upgrade

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#183]
In the spatialite 3 to 4 upgrade implemented in #182, the complete database schema is rebuilt. 

In the sample (spatialite 3) sqlite that we distribute, some columns (like `v2_global_settings.minimum_sim_time_step`) do not have a NOT NULL constraint, but in the upgrade the NOT NULL constraint will be added. If the sqlite happens to have a NULL in such a column, the user will get an exception.

The same situation might arise for different column types (CHAR to INT will not always work), invalid geometries or wrongly typed geometries.

All of these situations are already covered in checks, but some are exempt:

NULL checks
-  "v2_grid_refinement.refinement_level": "warning",
-  "v2_grid_refinement.the_geom": "warning",
-  "v2_grid_refinement_area.refinement_level": "warning",
-  "v2_grid_refinement_area.the_geom": "warning",

type checks
- "*.sewerage": "INFO",
- "v2_weir.external": "INFO",
- "v2_connection_nodes.the_geom_linestring": "info",

invalid geometry (ST_IsValid) or geometry type checks
- "v2_connection_nodes.the_geom_linestring": "info",
- "v2_grid_refinement.the_geom": "warning",
- "v2_grid_refinement_area.the_geom": "warning",
- "v2_dem_average_area.the_geom": "warning",
- "v2_surface.the_geom": "warning",
- "v2_impervious_surface.the_geom": "warning",

What should we do here?

**Comment by caspervdw** [comment]
Discussion 16-5:

*grid refinements*
Just delete these records; they are skipped anyway in the gridbuilder.

The rest: discuss with @martijn-siemerink  / @Jonasvsl

**Comment by caspervdw** [comment]
Discussion 16-5:

*grid refinements*
Just delete these records; they are skipped anyway in the gridbuilder.

The rest: discuss with @martijn-siemerink  / @Jonasvsl

**Comment by Patrick-Nijman** [comment]
@caspervdw I think this is already operational. Can we close it?
