### ISSUE TITLE
Support GPKG

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#192]
In our QGis plugin (modeller interface), we make extensive use of geopackage file. It has a good integration with QGis. Geopackage is an sqlite under the hood, with added support for geometry columns. Very much alike the spatialite format, but with a much broader support.

The spatialite driver has support for geopackage files, so you can actually read/write geopackage using SQL, mostly exactly like with spatialite files.

GeoAlchemy however has no support for geopackage, so we would need to fix that in geoalchemy, or 'roll our own' geometry support.

**Comment by caspervdw** [comment]
@Jonasvsl  Do you think threedi-modelchecker is used to interface with PostGIS? My guess is that we can safely remove that support.

**Comment by Jonasvsl** [comment]
please remove it's easier. We do not actively support postgis. 

What about gpkg support? or is that the same as spatialite?

**Comment by caspervdw** [comment]
> What about gpkg support? or is that the same as spatialite?

Although it is based on SQLite, nobody wrote an SQL driver for geopackage. So we would need to do that ourselves.

**Comment by Jonasvsl** [comment]
gpkg is the same as spatialite I thought? Can you ask on a forum whether there is SQL driver support for geopackage? It is hard to imagine that that wouldnt exist

**Comment by caspervdw** [comment]
No it’s not, they are both based on SQLite though. The geometry stuff is different. We would need a driver for that part only.

**Comment by caspervdw** [comment]
I started this by removing PostGIS support and investigating GPKG support.

Interfacing with GPKG is no problem, only the geospatial queries and migration of geometry columns don't work.

**Comment by leendertvanwolfswinkel** [comment]
Replaced by this epic: https://app.zenhub.com/workspaces/team-3di-5ef60eff1973dd0024268b90/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTY0OTg1
