### ISSUE TITLE
[3Di]: Rasterchecker - check DEM projection

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-modelchecker#195]
- [ ] https://github.com/nens/servicedesk-issue-only/issues/55

### What happened?

Emiel had een aantal simulaties gedraaid waarbij de naverwerking in Lizard niet goed ging.
Dit gaf de foutmelding: "RuntimeError: OGR Error: Corrupt data"
Bij het aanpassen van de DEM projectie werkte het weer naar behoren.

### How to Reproduce?

De originele en de DEM waarmee het wel werkte staan in de bijlage. 

### What did you expect and what was the actual result?

Dit moet gecheckt worden in de rasterchecker. Dit issue was erg lastig te debuggen. 

### Add screenshots, video's etc

[dem_brownhill_creek_correct.zip](https://github.com/nens/servicedesk-issue-only/files/8540907/dem_brownhill_creek_correct.zip)
[dem_brownhill_creek_old.zip](https://github.com/nens/servicedesk-issue-only/files/8540908/dem_brownhill_creek_old.zip)

**Comment by caspervdw** [comment]
I see no issues with the current old file. Indeed the projection is different; GDAL is unable to extract an EPSG code from the old file.

But that is no problem for our pipeline. On the Lizard side it seems to be fixed now by https://github.com/nens/raster-store/issues/182 (which was created on the same time? maybe also as a result of this bug report?)
