### ISSUE TITLE
[Bug]: Models double index on a table crash in the model creation

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#200]
### Complexity

easy

### Priority

medium prio

### What happened?

after uploading a schematisation and creating a model, the error returned is:

https://api.3di.live/v3/threedimodels/48053/tasks/

### How to Reproduce?

upload the above mentioned schematisation to production

### What did you expect and what was the actual result?

a threedimodel

### Add screenshots, video's etc

-

### Relevant log output

```shell
from Daan:
(sqlite3.OperationalError) there is already a table named idx_v2_impervious_surface_the_geom
[SQL: CREATE INDEX idx_v2_impervious_surface_the_geom ON v2_impervious_surface (the_geom)]
```

**Comment by caspervdw** [comment]
The issue seems to be about migration number 173 and occurs not only in this model (katvoed), also in beemster.sqlite e.g.

Sentry link: https://sentry.io/organizations/nens/issues/3477532840


Another affected model: https://api.3di.live/v3/threedimodels/51933  (beemster.sqlite)

**Comment by caspervdw** [comment]
This still requires a bump of the threedi-modelchecker version in the backend.
