### ISSUE TITLE
Surface map has obsolete attribute surface_type

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#209]
The column `v2_surface_map.surface_type` does not seem to be used at all. However, if the column is empty, an ERROR is reported. I propose:
- Check if `v2_surface_map.surface_type` is used in any way
- If not, remove this column and the check(s) associated with it
- If it _is_ used, we need to make some changes to the 3Di Schematisation Editor

**Comment by caspervdw** [comment]
The field is not being used. It is not even read by the gridbuilder (https://github.com/nens/threedigrid-builder/blob/master/threedigrid_builder/interface/db.py) --> we can remove it here.
