### ISSUE TITLE
Method to repair spatial indexes

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#216]
For check 201 we need a spatial index. Just as with the "set_views", modelchecker should be able to repair these.

There is code in the Toolbox that does this too: https://github.com/nens/ThreeDiToolbox/blob/d8e5827147acc43b7948306f37dce0b5d62399e2/utils/threedi_database.py#L183

@leendertvanwolfswinkel  is this code still in use? I think it is good to use the centralized code in this repo everywhere.

**Comment by leendertvanwolfswinkel** [comment]
Is my interpretation correct that instead of 

`ThreeDiToolbox.utils.threedi_database.ThreediDatabase.fix_spatial_indices()`

we should use 

`threedi_modelchecker.schema.ModelSchema.set_spatial_indexes()`

?

**Comment by caspervdw** [comment]
Yes indeed. 

The behaviour changed also:

- spatial indices are created, always
- They are not disabled afterwards
