### ISSUE TITLE
Raster checks

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#218]
3: Is the raster file extension .tif / .tiff?
4: Is the raster filename valid? (no special characters, no space, max one '.' and '/') -- In theorie mag hier nu gewoon een padverwijzing instaan (met meerdere slashes)
5: Is the raster single- (not multi-) band?
7: Does the raster have a projected coordinate system (unit: meters) Yep belangrijk
11: Are the pixels square -- Yep. Belangrijk!

**Comment by caspervdw** [comment]
https://github.com/nens/ThreeDiToolbox/issues/574

**Comment by Patrick-Nijman** [comment]
Closed, part of Release
