### ISSUE TITLE
Check: too many (impervious) surfaces mapped to one connection node

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#229]

**Comment by leendertvanwolfswinkel** [comment]
I think it is a good idea to check this separately from the total area. But 10 connections is too low for a threshold. If manholes are 50m apart and houses are 6 m wide & on both sides of the street, you would already have ~17 mappings on one connection node. I think we should only give warnings if it is really likely to be wrong.

I suggest a threshold of 50 mappings

**Comment by Patrick-Nijman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3Di-5ef60eff1973dd0024268b90/issues/nens/threedi-modelchecker/229?planning-poker) with Zenhub @elisallenens
