### ISSUE TITLE
Breach line table and checks

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#231]
@Jonasvsl @martijn-siemerink @leendertvanwolfswinkel 

Do we want a "breach point" and "breach line" table? I think it is not good to have more than one way to give a breach.

Is it feasible to only have a "breach line" table?

**Comment by Jonasvsl** [comment]
I think from a modellers perspective the breach line is preferred, it clearly shows where the water comes from and where it goes to

**Comment by caspervdw** [comment]
I agree, but in the design document (shadow line method) a "breach_point" is described.

- If the channel has a shadow line, the breach line specifies the 2D exchange location *again*. This could be inconsistent.
- The MI tooling that creates breaches would need a shadow line as input to correctly set the breach 2D end.

I think this is all perfectly feasible.

**Comment by Jonasvsl** [comment]
I described a line when communicating with Wouter, he was also strongly in favor of that. 

Regarding your first point:
- I think we said something to the extent that one supercedes the other  and we do not support the use of both at the same time

**Comment by caspervdw** [comment]
Some remaining questions:

- A potential_breach line should be drown from the channel to a 2D cell. How strict should we check that the potential breach startpoint (beginning of line string) is exactly at the channel? Point - on - linestring checks are pretty hard, best to have a tolerance here, I think.
- We can have 2 potential breaches at the same position, to be able to have 1 double connected node with 2 breaches. Is this even necessary? If yes, can we expect the user to snap the potential breaches starts to each other so that coordinates are exactly equal?
- We can have potential breaches at the channel start / end (it is transferred to the connection node in that case). Can we expect the user to snap the potential breach to the connection node?

@leendertvanwolfswinkel @Jonasvsl

**Comment by leendertvanwolfswinkel** [comment]
First point: we could make it a requirement that it starts at a channel vertex, just like cross section locations?

Second point: yes I think this should be possible (boezem die aan beide zijden zou kunnen falen). I think it is OK to have a "must start at same vertex if too close together" requirement for this use case.

I think forcing it to start at a channel vertex would solve point 3 as well? If it is too close to start/end node, an extra calculation point is not created, right?

**Comment by leendertvanwolfswinkel** [comment]
Reaction to earlier comment: I think it would be nice to have the option to use both exhange_line and potential_breach. Can't we just require the potential breach to end at (a vertex of) the exchange_line if it exists for that channel?

**Comment by caspervdw** [comment]
> First point: we could make it a requirement that it starts at a channel vertex, just like cross section locations?

CS locations can also be halfway two vertices, it just has to be 'on' the linestring. Because a point-on-line string is sensitive to imprecisions, we currently have a check that allows 1 meter distance. I did the same for the potential breaches. So that seems OK.

> Second point: yes I think this should be possible (boezem die aan beide zijden zou kunnen falen). I think it is OK to have a "must start at same vertex if too close together" requirement for this use case.

I currently consider 2 potential breaches that are < 2 meters apart to be 'the same'. But I am unable to perform a check then to see if there are clusters of >2 potential breaches. Depending on the calculation type of the channel, superfluous potential breaches will be ignored by gridbuilder in those cases. Requiring an exact equality of the potential breach start points would enable making checks.

> I think forcing it to start at a channel vertex would solve point 3 as well? If it is too close to start/end node, an extra calculation point is not created, right?

Forcing the potential breach to the the start/end vertex seems good, but there is currently a tolerance between the channel start and connection node point (tolerance of 1 meter); the user needs to snap to the channel and not to the connection node. This may be confusing. A check can help.

> Reaction to earlier comment: I think it would be nice to have the option to use both exhange_line and potential_breach. Can't we just require the potential breach to end at (a vertex of) the exchange_line if it exists for that channel?

We have this option, but there are no constraints on the potential breach 2D side. The potential breach just overrides the exchange line for that specific 1D-2D line.


**summarizing**

- Error when potential breach lines are not on a channel (allow 1m tolerance)
- Error when potential breach lines are <1 m from the start/end of a channel linestring
- Error when potential breach lines are spaced <1 m apart (except when they are on the same position on a double connected channel)
- Error when potential breach lines are on a non-connected channel (isolated/embedded)
- Error when there are clusters of more than 2 potential breaches on a double connected channel

**Comment by caspervdw** [comment]
Additional questions:

- do we validate `maximum_breach_depth` ? is there a valid range for that?
- do we validate `exchange_level`?

**Comment by caspervdw** [comment]
@martijn-siemerink can you propose a validation for maximum_breach_depth and exchange_level?
