### ISSUE TITLE
Exchange line table and checks

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#232]

**Comment by caspervdw** [comment]
@Jonasvsl  @martijn-siemerink 

About the name.

- `shadow_line`
- `exchange_line`
- `domain_exchange_line`

What do you think? I think I like `exchange_line`.

About the backwards compatibility:

Connected points can currently also apply to pipes, culverts and connection nodes (manholes and 1D boundary conditions). If we would let the shadow lines replace the connected points, that behavior will be gone.

We could extend the design to also be able to have shadow lines for pipes, culverts and connection nodes. But I don't know if that is necessary. We could also deprecate that.

**Comment by Jonasvsl** [comment]
exchange_line has a better ring to it than shadow line. 

not sure whether we need to extend the design to have shadow lines for pipes, culverts and connection nodes. @leendertvanwolfswinkel what do you think? I remember I had a nice theory about it being handy for connection nodes in urban areas but my assumptions where proven to be incorrect. So for me it is hard to see the benefit.

**Comment by caspervdw** [comment]
One question:

- I'd like to prevent the user from inserting the wrong channel id (otherwise you may connect entirely different model regions). Is a warning when the distance between exchange line and channel is too large a good idea? What threshold do we take?
@leendertvanwolfswinkel @Jonasvsl

**Comment by leendertvanwolfswinkel** [comment]
Sounds good, I would propose to use a pretty lange distance. We don't want a high number of false warnings. 

I think 500 m would be a good value? I.e. always wrong.
