### ISSUE TITLE
Migrate connected points to shadow lines / breach lines

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#233]

**Comment by caspervdw** [comment]
Some questions about what to clean:

- remove the v2_connected_pnt and v2_calculation_point tables (this drops the pipe & culvert displaced 1D-2D lines)
- remove the v2_levee material and max_breach_depth columns (they are moved to v2_potential_breach)
- merge the v2_obstacle and v2_levee tables: new table name is v2_obstacle (we have to reset the pks of one of the two, proposal is to reset the v2_obstacle ids)

@leendertvanwolfswinkel

**Comment by leendertvanwolfswinkel** [comment]
Sounds good to me
