### ISSUE TITLE
potentially a warning should be set to Error

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#235]
We hadden een klein issue met het cursus model:
https://management.3di.live/schematisations/5119/44498

Het model rekende niet en ga de volgende melding:
https://api.3di.live/v3/simulations/104609/status/history/

Er zaten een paar warnings in die ik allemaal weggehaald heb.
Daarna rekende het model

Er zit een verschil tussen revisie 5 en 6 waardoor het model wel rekent.

Ik heb vrij lomp alle connection nodes met NULL storage 1 m2 storage gegeven. En manhole storage area op NULL gezet.

Welke van deze twee meldingen zou op ERROR moeten komen te staan? Er is blijkbaar een verschil tussen de rekenkern image die tijdens de vorige cursus gebruikt is en de huidige cursus waardoor 1 van de warnings dus toch ernstiger is. 

Hier de meldingen van de schematisatie checker van revisie 5:
level,error_code,id,table,column,value,description
WARNING,"252","7448",v2_pipe,id,"7448","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7449",v2_pipe,id,"7449","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7450",v2_pipe,id,"7450","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7451",v2_pipe,id,"7451","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7452",v2_pipe,id,"7452","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7453",v2_pipe,id,"7453","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7454",v2_pipe,id,"7454","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7455",v2_pipe,id,"7455","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7457",v2_pipe,id,"7457","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7458",v2_pipe,id,"7458","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"252","7459",v2_pipe,id,"7459","When connecting two isolated pipes, it is recommended to add storage to the connection node."
WARNING,"321","1",v2_global_settings,manhole_storage_area,"100.0",sub-basins (v2_global_settings.manhole_storage_area > 0) should only be used when there is no DEM supplied and there is no 2D flow

**Comment by caspervdw** [comment]
Het punt is dat deze situatie SOMS tot crashes leidt, maar niet altijd.

Wil je dat alle modellen stoppen omdat het mogelijk fout kan gaan? Elke warning -> error vervanging is backwards incompatible en leidt tot errors bij modellen die eerst wel werkten.

@Jonasvsl
