### ISSUE TITLE
Check if settings records are used

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#236]
If e.g. a record in the v2_simple_infiltration table exists but is not referenced from v2_global_settings, please show this. I think it should be INFO level, because it _may_ be a perfectly valid and intended thing to do

**Comment by Jonasvsl** [comment]
similar to? https://app.zenhub.com/workspaces/nelen-en-schuurmans-overview-628211daedba7600185a165a/issues/gh/nens/threedi-modelchecker/168

**Comment by caspervdw** [comment]
Duplicate of #168
