### ISSUE TITLE
check inflow area per connection node. if larger than x m2., then a warning saying that the user should check storage in the node

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#243]

**Comment by Jonasvsl** [comment]
similar to #229

**Comment by caspervdw** [comment]
I don't think it is similar to #229. Please add the threshold to this ticket, then we can pick it up.

**Comment by Jonasvsl** [comment]
@leendertvanwolfswinkel what is a large realistisc m2 inflow connected to a node? 10.000 m2?

**Comment by leendertvanwolfswinkel** [comment]
I did some simple calculations on a 'typical' sewer system situation and I think 10,000 m2 is a good threshold for this warning

**Comment by Jonasvsl** [comment]
thanks!

@caspervdw  see answer above

**Comment by Patrick-Nijman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3Di-5ef60eff1973dd0024268b90/issues/nens/threedi-modelchecker/243?planning-poker) with Zenhub @elisallenens

**Comment by elisallenens** [comment]
Closing manually because the new relevant PR, #302, was merged before being linked.
