### ISSUE TITLE
check storage area at node pump is sufficient (empty pump cellar in some time, not one timestep);

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-modelchecker#245]
@Jonasvsl commented on [Mon Nov 14 2022](https://github.com/nens/threedi-api/issues/1805)

**Comment by caspervdw** [comment]
@Jonasvsl  Can you add a threshold value here? And want to you mean by "in some time, not one timestep"?

**Comment by elisallenens** [comment]
In v2_bergermeer, the pumpstations with the id 13 and 10 (and possibly others as well) do not have any manholes attached, and the connection nodes at each end of the pumpstation have their storage_area set to NULL. Where should the storage area for these pumps be calculated from?

**Comment by elisallenens** [comment]
@Jonasvsl do you know?

**Comment by Jonasvsl** [comment]
tbh I don't know. but I realize now that the requirement that we stated is for urban sewerage models. I think it is fair for now to leave out of the check pump stations that are in open water. 
@martijn-siemerink agree?

**Comment by elisallenens** [comment]
The only issue is that pumpstations are not currently marked as being part of a sewerage model or not. Leendert suggests adding the sewerage field to each pumpstation for this, so that the user can indicate whether a pumpstation is part of a sewer or not. @caspervdw opinions?

**Comment by caspervdw** [comment]
We normally distinguish open water from sewerage by looking at “storage_area”. If it is nonzero, we say it is sewerage.

What I don’t understand is that this check is about the storage_area being sufficiently large, while apparently nodes without any storage (open water) are OK. So a pump needs either 0 storage on the node, or a lot. Am I missing something here?

**Comment by elisallenens** [comment]
If I understood Leendert correctly, the point is not that the open water nodes are OK, but that they're a lot harder to calculate, because there the storage is the channels etc attached to the pump, rather than a manhole of known storage area.

**Comment by elisallenens** [comment]
After discussing with with Casper, we concluded that the check should not be conditional on the pump being for sewage, but on the pump having an associated defined storage area such as via a manhole, rather than a storage area that needs calculating from pipe profiles and other hairy monsters of the imagination.

**Comment by leendertvanwolfswinkel** [comment]
Feedback from users is that the calculation in this check is wrong. Apparently the connection node storage are is not taken into account in the calculation. @elisallenens can we please check this together?

**Comment by elisallenens** [comment]
Sure, I'll message you in Teams.

**Comment by elisallenens** [comment]
Fixed in #313.
