### ISSUE TITLE
Lower_stop_level < bottom_level is een issue

### ISSUE THREAD

**Issue by arnoldvantveld** [nens/threedi-modelchecker#25]
https://github.com/nens/threedi-modelchecker/blob/0770425648a0f0b5fa8b8558bb5f13927035edef/threedi_modelchecker/config.py#L383

**Comment by arnoldvantveld** [comment]
In dit stukje code zou de check volgens mij moeten zijn of de bottom_level > lower_stop_level.
Nu komt tie verkeerd uit de schematisatie checker in de plugin.

**Comment by RichardB9** [comment]
Goed gevonden en bedankt voor de feedback! Ik heb fix gemaakt eneen nieuwe release van de threedi-modelchecker. Deze wordt ook meegenomen in de ThreediToolbox wanneer daar weer een nieuwe release van komt.

**Comment by lisannewapstra** [comment]
@reinout  deze moet gemerged zijn, maar niet in master teruggekomen. Kan jij dit achterhalen en goed zetten? En ook checken of andere merges goed zijn doorgekomen?

**Comment by caspervdw** [comment]
De fix is wel in master teruggekomen, maar weer teruggedraaid in https://github.com/nens/ThreeDiToolbox/issues/503 . 

> (Richard) In a correct 3di model the following condition should hold: "Pumpstation.lower_stop_level > Manhole.bottom_level"
> (Jonas) yes your statement is correct

> (Arnold) In dit stukje code zou de check volgens mij moeten zijn of de bottom_level > lower_stop_level.

We kunnen niet allebei implementeren. Zeg het maar, wie heeft gelijk?

**Comment by caspervdw** [comment]
Definitive answer: Afslagpeilen (lower_stop_level and upper_stop_level) must be above bottom level.
@Jonasvsl

**Comment by arnoldvantveld** [comment]
@caspervdw in de bovenstaande hebben beide gelijk.
lower_stop_level must be above manhole.bottom_level
de check moet dan zijn
bottom_level is be above lower_stop_level and upper_stop_level -> than error!
since this is incorrect.

**Comment by arnoldvantveld** [comment]
Wat is de code die nu geïmplementeerd gaat worden?

**Comment by caspervdw** [comment]
@arnoldvantveld  Ik zal je assignen als reviewer van het pull request

**Comment by arnoldvantveld** [comment]
Ja is goed!

**Comment by caspervdw** [comment]
@arnoldvantveld  @Jonasvsl  Ik heb mezelf er net van overtuigd dat de huidige implementatie correct is.

De check ziet er zo uit:

```
QueryCheck(
        column=models.Pumpstation.lower_stop_level,
        invalid=Query(models.Pumpstation).join(
            models.ConnectionNode,
            models.Pumpstation.connection_node_start_id == models.ConnectionNode.id
        ).join(
            models.Manhole
        ).filter(
            models.Pumpstation.lower_stop_level <= models.Manhole.bottom_level,
        ),
        message="Pumpstation.lower_stop_level should be higher than "
                "Manhole.bottom_level"
    ),
```

Vertaald betekent dat dat het invalid is als lower_stop_level lager of gelijk is aan manhole bottom level.

Ik het het zelfs getest met v2_bergermeer, daar zit 1 "Rioolgemaal"in met lower_stop_level = -4.78, en die zit (met de start_id) vast aan een manhole met bottom level van -5. De checker geeft geen errors op het model, wat allemaal klopt.

**Comment by caspervdw** [comment]
Of is het hele issue dat `>=` een `>` moet worden? Met andere woorden dat het afslagpeil gelijk mag zijn aan de bodem van de put?

**Comment by Jonasvsl** [comment]
nee het moet groter zijn. Ik heb een model van Medemblik waarin de melding wel foutief optreedt

**Comment by caspervdw** [comment]
Volgens mij ligt dit allemaal veel genuanceerder. Een pumpstation heeft 2 connection_nodes, beiden mogelijk met een manhole (en dus een bottom level).

Het afslagpeil (lower_stop_level) moet boven het bottom_level liggen aan de kant waar het afslagpeil geldt. Dit hangt af van het type, `SUCTION` of `DELIVERY`.

**Comment by Jonasvsl** [comment]
klopt helemaal. overigens is in de meeste gevallen (99%) een pomp gebaseerd op de suction side

**Comment by caspervdw** [comment]
Maar in veel gevallen zal hij pumpen naar een manhole met een hogere bottom level, misschien wel hoger dan het afslagpeil. Hier komt het issue vandaan.

Toevallig had ik medemblik lokaal staan, ik kon het reproduceren en met de PR die k zo maak is het opgelost.

**Comment by Jonasvsl** [comment]
top!

**Comment by arnoldvantveld** [comment]
@caspervdw aah zat het daarin! Scherp gezien casper!
Volgens mij klopt het nu helemaal!

Vele modelleurs zullen je, zonder dat ze het door hebben, erg dankbaar zijn!
