### ISSUE TITLE
Check if all aggregation settings have been filled in that are required for using the water balance tool

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#253]
WARNING level

**Comment by Jonasvsl** [comment]
@leendertvanwolfswinkel  why don't we make this a standard setting in the modeller interface wizard ?

[] create aggregration settings for the water balance tool 
If the appropriate settings are already there the box is unchecked, but if it's lacking this is the easiest way to be able to use the water balance tool

A maybe better alternative is the add a button in the schematisation editor in the appropriate table: 'fill aggregation table with default aggregation settings'

**Comment by Jonasvsl** [comment]
The check that we then can do is:
- Are the aggregation settings all having the same time step 
- Are the aggregation time steps similar to the output timestep and/or higher?

**Comment by leendertvanwolfswinkel** [comment]
I think we should indeed make it easy for users to fill in the aggregation settings that are required for the water balance tool. But we also need a check.

More generally, what I would really like to have / work towards, is having a processing algorithm matching each error/warning generated by the schematisation checker. We can include the error code in the name of the processing algorithm, so that it is easy to find.

**Comment by leendertvanwolfswinkel** [comment]
yes

**Comment by Patrick-Nijman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3Di-5ef60eff1973dd0024268b90/issues/nens/threedi-modelchecker/253?planning-poker) with Zenhub @elisallenens

**Comment by elisallenens** [comment]
Is the issue
> The check that we then can do is:
> 
> Are the aggregation settings all having the same time step?
> Are the aggregation time steps similar to the output timestep and/or higher?
or
> More generally, what I would really like to have / work towards, is having a processing algorithm matching each error/warning generated by the schematisation checker. We can include the error code in the name of the processing algorithm, so that it is easy to find.
?

The first should be doable; it's very similar to https://github.com/nens/threedi-modelchecker/pull/292. The second could take a bit longer.

**Comment by leendertvanwolfswinkel** [comment]
@elisallenens this ticket is just about checking things; the discussion about possible fixes is interesting & important, but not within the scope of this ticket. In terms of checks, three different things are mentioned in this ticket:
- [ ] Do the aggregation settings all have the same time step?
- [ ] Are the aggregation time steps >= output timestep?
- [ ] Have all aggregation settings been filled in that are required for using the water balance tool?

**Comment by elisallenens** [comment]
note to self: the settings required to use the water balance tool are listed at https://docs.3di.live/i_analyzing_results.html#waterbalanceactivate

**Comment by elisallenens** [comment]
The first two checks are very easy, @leendertvanwolfswinkel , so I've written them. The third check is already implemented in the water balance tool:
https://github.com/nens/ThreeDiToolbox/blob/78b93fd2ca8909436d2ed5153d2cf0b1b71ef7ef/tool_water_balance/tools/waterbalance.py#L956-L1047
which raises a clear error showing which variables still need to be filled in:
https://docs.3di.live/i_analyzing_results.html#using-the-water-balance-tool
Since which variables are required depends on multiple factors in the database, the check is quite complex, and I see no added value in re-implementing it in the modelchecker.
