### ISSUE TITLE
[REQ] Check voor connected nodes buiten de calculation cells

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-modelchecker#260]
Hallo,

Tijdens het uploaden van een model krijg ik de volgende melding:

![image](https://user-images.githubusercontent.com/86961942/212031657-a49a902b-4c4e-4f24-92ee-22324e81608c.png)

Er zijn een aantal elementen buiten de 2D calculation cells die op connected staan.
Dit is goed op te lossen, maar mijn vraag is of het mogelijk is dat we deze melding al krijgen bij het uitvoeren van
de schematisatiechecker, zodat je deze aanpassingen meteen kunt maken in de geopackage.

**Comment by Patrick-Nijman** [comment]
Het probleem is dat we deze check pas kunnen doen als de GridAdmin gemaakt is. En dat doen we niet bij een normale upload. Dit gaan we waarschijnlijk aanpassen dus wellicht dat deze check dan wel gemaakt kan worden.

**Comment by caspervdw** [comment]
Duplicate of https://github.com/nens/threedi-modelchecker/issues/79
