### ISSUE TITLE
Check that ids are < 32 bit integer

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#303]
ID values for all tables should be within 32 bit integer range

**Comment by elisallenens** [comment]
@leendertvanwolfswinkel For v2_orifice, for instance, the id typeset in the database is a 64-bit integer. Is there a reason it has to be 32-bit?
Also, is it supposed to be a signed or unsigned 32-bit integer?

**Comment by elisallenens** [comment]
Discussed it with Casper, apparently it's supposed to be a positive signed 32-bit integer.
