### ISSUE TITLE
Warnings for short orifices and weirs should not be issued

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#321]
Recently, check 202 was changed in such a way that warnings are issued when channels, pipes, or culverts are shorter than 5 m. However, it now also gives these warnings for orifices and weirs. This is wrong.

   * - 0202
     - Warning
     - The length of v2_orifice is very short (< 5 m). A length of at least 5.0 m is recommended to avoid timestep reduction.
   * - 0202
     - Warning
     - The length of v2_weir is very short (< 5 m). A length of at least 5.0 m is recommended to avoid timestep reduction.

**Comment by caspervdw** [comment]
I think you are meaning check 204. This warns if a weir/orifice is broad crested and shorter than 5 m.

**Comment by leendertvanwolfswinkel** [comment]
If it is broad crested and shorter than 5 m, a warning should be issued, so no changes needed for 204. 202 is the one that gives the wrong warnings

**Comment by caspervdw** [comment]
202 only gives warnings on channel and culvert tables.

Can you provide the files that reproduce the issue?
