### ISSUE TITLE
Conveyance checks (ERROR level)

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#323]
Currently, we have two friction types, Chézy (1) or Manning (2)

Two new friction types will be introduced for 1D:
- Chézy with conveyance (3) 
- Manning with conveyance (4)	

These friction types are valid only for cross sections that meet the following criteria:
- Tabulated rectangle, tabulated trapezium, or YZ 
- At each higher height, the width stays the same or increases (>=). I.e. the cross-section never becomes narrower when going up. The new friction types cannot be used for closed cross-sections.
- The new friction types can only be used for `v2_cross_section_location` 

Checks need to be added for these criteria. Please raise an error if any invalid combination is used.

**Comment by Patrick-Nijman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3Di-5ef60eff1973dd0024268b90/issues/nens/threedi-modelchecker/323?planning-poker) with Zenhub @elisallenens

**Comment by elisallenens** [comment]
These are done, but they're on the same branch that I'm putting the checks for #325 on, https://github.com/nens/threedi-modelchecker/tree/conveyance-checks, so I'll merge it when they're done.
