### ISSUE TITLE
Add `set_gate_height` to allowed control structure actions

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#334]
Currently:
- set_discharge_coefficients
- set_crest_level
- add set_gate_height to this list
- 
https://github.com/nens/threedi-schema/blob/67f90a89b4e9d8cafd0ae581f5245a7e866879e0/threedi_schema/domain/constants.py#L216

**Comment by daanvaningen** [comment]
automatically picked up threedi-schema configuration

**Comment by leendertvanwolfswinkel** [comment]
@daanvaningen please also update the documentation for the various endpoints to include the `set_gate_level` option
