### ISSUE TITLE
Check if pipe or culvert has Open Rectangle (shape = 1)

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#335]
If v2_pipe or v2_culvert has shape = 1 (open rectangle), please give the following message (INFO level):

"Cross-section shape "open rectangle" (1) is unusual for pipes and culverts. Perhaps you meant to use "closed rectangle" (2)?"

**Comment by elisallenens** [comment]
@leendertvanwolfswinkel shouldn't this be checked on all open profiles as defined in #323?
