### ISSUE TITLE
Schematisation checks for variable roughness in YZ profiles

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#339]
When we allow users to use variable roughness and vegetation parameters in YZ profiles (nens/threedi-schema#42), this also has implications for `threedi-modelchecker`.

I can think of the following checks. What is written below also applies to all the vegetation parameters in nens/threedi-schema#42. 

**New checks**
- [ ] Variable friction cannot be used in combination with closed YZ profiles. In other words, if variable friction is used, the YZ profile must be monotonically increasing
- [ ] The number of values in `v2_cross_section_location.friction_values` must equal the number of segments in the YZ profile, i.e. number of YZ coordinates -1
- [ ] There are probably also a few more basic checks to be performed on these new fields, please make suggestions for this.

**Changes to existing checks**
- [ ] If `v2_cross_section_location.friction_values` (plural) is used, checks for `v2_cross_section_location.friction_value` (singular) should no longer be performed

**Comment by GolnesaK** [comment]
Show the following 'warning/recommendation' for the 'simpleness' of cross-section definitions by the users.
The content of the message should be: 
'Avoid using too many lines for a clearer cross-section definition, unless distinct friction/vegetation properties are assigned. For instance, merge/omit a segment if:

- a segment's length is below 5% of the total width of the channel
- the interior angle between two adjacent segments is higher than 160 degrees.'

**Comment by margrietpalm** [comment]
@leendertvanwolfswinkel @GolnesaK is there (already) some documentation about what the variable roughness is supposed to do? That could help me understand better what checks are needed.

**Comment by margrietpalm** [comment]
Change: 

- [ ]  If v2_cross_section_definition.friction_values (plural) is used, checks for v2_cross_section_location.friction_value (singular) should no longer be performed

**Comment by margrietpalm** [comment]
Valid friction types with variable friction: 1, 2, 3, 4. Conditions:

*Friction values*:
- 1 or 2: no plurals in definitions, but singulars in location
  - warning in case of plurals (parameters will not be used)
- 3 or 4: both plurals and dingulars are valid; plurals take priority. There must be a value.
  - warning in case of singulars (parameters will not be used)

*Vegetation*:
Same as Friction Values, but types 2 and 4 are invalid. Results in error (use type 1 / 3, vegetation cannot be used with friction type)
