### ISSUE TITLE
Warning is incorrectly given when interception_global = 0.0

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#340]
There is a check for global values (like `interception_global`) for which also a raster file is supplied (like `interception_file`). If the global value is `NULL`, a warning is given. 

However, if `interception_global` = 0.0, it also gives this warning. Perhaps a case of `if not interception_global:` that evaluates to `False` for `0.0`?

I guess that the same issue exists also for all other "global" values

**Comment by elisalle** [comment]
@leendertvanwolfswinkel do you have an example? In the code for NotNullCheck, the value is explicitly compared against `None`:
https://github.com/nens/threedi-modelchecker/blob/ffeb35c19a2e801cf3a085c056de868cc06821ae/threedi_modelchecker/checks/base.py#L207

**Comment by leendertvanwolfswinkel** [comment]
[Calamiteitenmodel_Delfland.zip](https://github.com/nens/threedi-modelchecker/files/13203145/Calamiteitenmodel_Delfland.zip)
