### ISSUE TITLE
Remove check 0029

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#358]
This is a check that gives an INFO level warning "Friction for this cross-section will be calculated without conveyance. For open Tabulated or YZ cross-sections, using conveyance in the calculation of friction is recommended in case there is a significant variation of the bed level (for instance, in a scenario with overflowing floodplains)."

This was introduced a few months ago, but it is annoying to many users; instead, we will provide this guidance in the documentation.

**Comment by daanvaningen** [comment]
api is on 2.5.1
