### ISSUE TITLE
AttributeError: 'CrossSectionDefinition' object has no attribute 'vegetation_drag_coefficient'

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#368]
When running the schematisation checker in QGIS, I get the error shown below. Not sure where the cause is (threedi-schema/threedi-modelchecker/implementation in QGIS).

Versions used:
`threedi-schema 0.219.2`
`threedi-modelchecker 2.6.2`

Data:
[Testbank testje 702 1D vegetatie Chézy.zip](https://github.com/nens/threedi-modelchecker/files/14994876/Testbank.testje.702.1D.vegetatie.Chezy.zip)

```
QGIS version: 3.34.4-Prizren
QGIS code revision: decd43dc
Qt version: 5.15.3
Python version: 3.9.18
GDAL version: 3.8.4
GEOS version: 3.12.1-CAPI-1.18.1
PROJ version: Rel. 9.3.1, December 1st, 2023
PDAL version: 2.6.0 (git-version: 3fced5)
Algorithm started at: 2024-04-16T11:35:11
Algorithm 'Check Schematisation' starting…
Input parameters:
{ 'ADD_TO_PROJECT' : True, 'INPUT' : 'C:\\Users\\leendert.vanwolfswin\\Documents\\3Di Staging\\Testbank testje 702 1D vegetatie Chézy\\work in progress\\schematisation\\Testbank testje 702 1D vegetatie Chézy.sqlite', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Traceback (most recent call last):
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\Schema 219/python/plugins\threedi_results_analysis\processing\schematisation_algorithms.py", line 214, in processAlgorithm
getattr(error_row, check.column.key),
AttributeError: 'CrossSectionDefinition' object has no attribute 'vegetation_drag_coefficient'

Execution failed after 1.79 seconds

Loading resulting layers
Algorithm 'Check Schematisation' finished
```

**Comment by elisalle** [comment]
De simpele oplossing is om
https://github.com/nens/threedi-modelchecker/blob/7664e375944077095af51ce9b7479081ab034662/threedi_modelchecker/config.py#L2953-L2958
te veranderen naar
```py
        invalid=Query(models.CrossSectionLocation)
        .join(
            models.CrossSectionDefinition,
            models.CrossSectionLocation.definition_id
            == models.CrossSectionDefinition.id,
        )
```
alleen zou dat helemaal niet uit horen te maken.
Er gebeurt iets vreemds met de column namen in QueryChecks. Wanneer je bijvoorbeeld als column naam opgeeft `models.CrossSectionLocation.vegetation_drag_coefficient` maar de eerste tabel in je Query is `models.CrossSectionDefinition` dan maakt de QueryCheck er automatisch `models.CrossSectionDefinition.vegetation_drag_coefficient` van. Misschien moet hier wat mee gebeuren.

**Comment by leendertvanwolfswinkel** [comment]
@elisalle what's the status on this? I suppose it is Ready for review?

**Comment by leendertvanwolfswinkel** [comment]
This must be released in a version of threedi-modelchecker that is compatible with schema 219.x

**Comment by elisalle** [comment]
> @elisalle what's the status on this? I suppose it is Ready for review?

yes, it is
