### ISSUE TITLE
Checker: inconsistent schematisation settings

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#56]
~- A non existing reference to Groundwater, SimpleInfiltration or Inception~
~- Incompletely filled Groundwater settings (only hydro_connectivity is optional)~
- Incompatible model type (combination of use_1d_flow / use_2d_flow / manhole_storage_area / dem_file )
-> blocked by 

- [ ] https://github.com/nens/threedigrid-builder/issues/86 
- [ ] https://github.com/nens/threedigrid-builder/issues/87

Associated Inpy code: https://github.com/nens/threedi/blob/b5748978ddcf67e08d343994b8273c0784ea4529/lib/threedi-spatialite-tools/threedi_spatialite_tools/threedi_files/detector.py#L37

The following combinations currently lead to an error:

- use_1d_flow, use_2d_flow, not dem_file, manhole_storage_area > 0
- use_1d_flow, not use_2d_flow, any dem_file, manhole_storage_area > 0
- not use_1d_flow, use_2d_flow, not dem_file, not manhole_storage_area
- not use_1d_flow, not use_2d_flow, any dem_file, any manhole_storage_area

Check that:
- manhole_storage_area > 0: expect no dem_file, no use_2d_flow, yes use_1d_flow -> if not, then warning
- use_2d_flow is True: expect a dem_file -> if not then error
- use_1d_flow and use_2d_flow cannot both be false (error if that occurs)

**Comment by Patrick-Nijman** [comment]
Still blocked by an open issue. If you use a task list for the blocking issues it's easier to see if all blocking issues are already closed.
