### ISSUE TITLE
Support "warning" and "info" levels for checks.

### ISSUE THREAD

**Issue by jpprins1** [nens/threedi-modelchecker#73]
We want to support "warning" and "info" levels for checks.

**Info**
Checks are not really problems, but more best practice/advise.

**Warning**
Checks that become errors after certain period of time. 

**Error**
Need to be fixed before 3Di model can be created.

_Note: Assigning levels to checks is a separate task._

**Comment by nvolp** [comment]
zie branch nici_checklevels.
