### ISSUE TITLE
Check for levee / 2D boundary condition / connected/embedded objects outside a DEM

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#79]
Request from user (Wouter in this case):

Can we add a check to see if the levee is outside a DEM?

**Comment by caspervdw** [comment]
No we do not have access to the DEM in the model checker. Going through mega/gigabytes of faster data to check for no data is a bit too much for a check.

What we could do instead is include the 2D model area (multipolygon) inside the SQLite. This may be used to mask the DEM when building the grid and tables. I like that idea because it makes the SQLite fully descriptive of the model; the DEM is then only needed to fill the tables, inactivate some cells/lines, and set bottom levels.

**Comment by Patrick-Nijman** [comment]
@Jonasvsl  Even reactie teruggeven aan gebruikers

**Comment by martijn-siemerink** [comment]
I think all these things are now covered in Klondike release. Levee and connected objects can be placed outside DEM. (connected will get a very high exchange level, since no data is present.) Other things are validated in threedigrid-builder to my knowledge.

**Comment by Jonasvsl** [comment]
please add to the document with release notes if it is not there already. then we can close this ticket

**Comment by Jonasvsl** [comment]
@martijn-siemerink did we test the placing of levees outside the DEM? 
@caspervdw is Martijns assumption correct about the validation in the threedgrid builder?

**Comment by leendertvanwolfswinkel** [comment]
> I think all these things are now covered in Klondike release. Levee and connected objects can be placed outside DEM. (connected will get a very high exchange level, since no data is present.) Other things are validated in threedigrid-builder to my knowledge.

Placing connected channels outside of the DEM extent will not result in a valid model. I ran into this issue last December; making this possible would actually be quite a useful feature when making dike breach models.

**Comment by caspervdw** [comment]
So if a connected object is placed outside of the DEM (more precisely, outside of the 2D grid cells), then we can 'just' make no 1D-2D connection and effectively make the channel (partially) isolated. Is that ok?

For levees it has to be checked, I think it is already working if there is a levee outside of the DEM.

**Comment by Jonasvsl** [comment]
I think making it (partially) isolated is the most logical thing to do

Concerning manholes the wish would be different, but that is out of scope for this ticket

**Comment by leendertvanwolfswinkel** [comment]
I agree on making it partially isolated. With a warning produced by `threedigrid_builder`.

If the (closest point on the) exchange line is within the 2D grid, there should be no problem at all I think, and the connections could still be made
