### ISSUE TITLE
manhole bottom_level checks for 1D2D connections

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#93]
In gridbuilder there is the ~error~warning:

```
f"Connection nodes {sorted(ids.tolist())} have a manhole with a "
            f"bottom_level that is above one ore more of the following connected "
            f"objects: channel reference level, pipe/culvert invert level, "
            f"weir/orifice crest level."
```

There should be some equivalent here.

**Comment by Jonasvsl** [comment]
@caspervdw can you elaborate on this a bit more? I need more context

**Comment by caspervdw** [comment]
gridbuilder logs a warning if there are manholes with a bottom level above a channel / pipe / culvert / weir/ orifice.

modelchecker should have these warnings too.

**Comment by elisallenens** [comment]
This is covered in the following checks:
I109: channel start reference level
I110: channel end reference level
W102: pipe, culvert invert level start point
W103: pipe, culvert invert level end point
W108: weir, orifice crest level
