### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-modelchecker#99]
We should investigate https://www.sqlite.org/security.html and implement recommendations in paragraph 1.2 @jpprins1

**Comment by jpprins1** [comment]
Good find! Looks like it's just adding some statements in the connection setup, let's try if that works out of the box. 

If not, let's create a ticket with a middle/high prio to address this. I would say this is not a critical risk (we don't process random sqlites, but only the ones provided by paying customers) however it's high enough and it's also good practice to harden your services.

Note: In all cases it might be a good thing to state somewhere that `threedi-modelchecker` users should be cautious with opening random sqlites with this package?
